Allow desktop build to change LD_LIBRARY_PATH
:Release Notes:
Now we can start JS apps under desktop build.

:Detailed Notes:
Without this change all apps reports that they unable to find
pmloglib:

node.js:144
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: libPmLogLib.so.3: cannot open shared object file: No such file or directory
    at Object..node (module.js:420:11)
    at Module.load (module.js:340:31)
    at Function._load (module.js:301:12)
    at require (module.js:352:19)
    at Object.<anonymous> (/mnt/devel/build/build-luna-surface-manager-desktop/build/rootfs/usr/palm/services/jsservicelauncher/bootstrap-node.js:129:53)
    at Module._compile (module.js:408:26)
    at Object..js (module.js:414:10)
    at Module.load (module.js:340:31)
    at Function._load (module.js:301:12)
    at Array.<anonymous> (module.js:427:10)

:Testing Performed:
No errors logged for JS services.

:QA Notes:

:Issues Addressed:

Open-webOS-DCO-1.0-Signed-off-by: Nikolay Orliuk <nikolay.orliuk@lge.com>

Change-Id: I04542abb2f183837586a3e161375d08374385b81
Reviewed-on: https://g2g.palm.com/3551
Reviewed-by: Build Verification
Reviewed-by: Nikolay Orliuk <nikolay.orliuk@lge.com>
Reviewed-by: Mark Bessey <mark.bessey@lge.com>
Tested-by: Mark Bessey <mark.bessey@lge.com>